#
#  Comaint Project
#  Copyright (C) 2023-2024 Dominique Parisot
# 
#  config.yml
# 
#  This program is free software: you can redistribute it and/or modify it under the terms of the 
#  GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
#  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 

name: "comaint"

attributes:
  backend_project_name: "Comaint API backend"
  backend_project_dir: "comaint-backend"
  backend_project_version: "0.0.2"
  backend_project_description: "API server of Comaint project"

  database_name: "db_comaint"
  database_schema_version: "1"
  api_version: "v1"
  frontend-project : "comaint-frontend"
  compagny: "Comaint"
  company: "Comaint"
  conception: "Powimod"
  authors: "Dominique Parisot"
  copyright: "2023-2024"
  license: "GPL V3 or later"
  lang: "fr"
  website: "https://github.com/powimod/comaint"
  contact: "powimod@gmail.com"

  root_object: 'Company'

objects:

  - name: "Company"
    attributes:
      table_name: "companies"
    properties:
      - name: "id"
        type: "id"
      - name: "name"
        type: "string"
        minimum: 2
        maximum: 128

  - name: "User"
    attributes:
      table_name: "users"
    properties:
      - name: "id"
        type: "id"
      - name: "email"
        type: "email"
        minimum: 3
        maximum: 128
      - name: "password"
        type: "string"
        secret: true
        minimum: 8
        maximum: 70 # 61 is the minimum size of bcrypt hash
      - name: "firstname"
        type: "string"
        mandatory: false
        maximum: 30
      - name: "lastname"
        type: "string"
        mandatory: false
        maximum: 30
      - name: "state"
        type: "integer"
        default: 0
        minimum: 0 
        maximum: 99999
      - name: "lastUse"
        type: "datetime"
        mandatory: false
      - name: "administrator"
        type: "boolean"
        default: false
      - name: "manager"
        type: "boolean"
        default: false

      - name : "authAction"
        scope: "protected"
        mandatory: false
        type: "string"
        maximum: 16
      - name : "authData"
        scope: "protected"
        mandatory: false
        type: "string"
      - name : "authCode"
        scope: "private"
        mandatory: false
        type: "integer"
        default: 0
        minimum: 0 
        maximum: 99999
      - name: "authExpiration"
        scope: "protected"
        mandatory: false
        type: "datetime"
      - name: "authAttempts"
        scope: "protected"
        mandatory: false
        type: "integer"
        default: 0

    links:
      - name: "company"
        target: "Company"
        mandatory: false
    indexes:
      - name: "email"
        unique: true
        keys:
          - property : "email"
      - name: "idx_company_lastname_firstname"
        unique: true
        keys:
          - link: "company"
          - property : "lastname"
          - property : "firstname"
      - name: "idx_company"
        unique: false
        keys:
          - link: "company"

  - name: "Token"
    attributes:
      table_name: "tokens"
    properties:
      - name: "id"
        type: "id"
      - name: "expires_at"
        type: "datetime"
    links:
      - name: "user"
        target: "User"
    indexes:
      - name: "idx_user"
        unique: false
        keys:
          - link: "user"


files:
  - scope:  "project"
    input:  "common/init-db.sql.liquid"
    output: "build/init-db.sql"

  - scope:  "project"
    input:  "common/clear-db.sql.liquid"
    output: "build/clear-db.sql"

  - scope:  "object"
    input:  "common/object-def.js.liquid"
    output: "build/common/src/objects/{{object.name | kebabCase}}-object-def.mjs"


